version: 2
jobs:
  build:
    working_directory: ~/sde-frontend
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Installations 
          command: npm ci
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Client
          command: npm run build